<?php

/**
 * PluginsfFacebookUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfFacebookUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfFacebookUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfFacebookUser');
    }
}