<?php

/**
 * PluginsfGuardFacebookUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardFacebookUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardFacebookUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardFacebookUser');
    }
}