<?php

/**
 * PluginsfGuardUserFacebookProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserFacebookProfileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserFacebookProfileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserFacebookProfile');
    }
}