sfGuardFacebookUser:
  actAs: [Timestampable]
  columns:
    uuid: string(255)
    first_name: string(255)
    last_name: string(255)
    link: string(255)
    timezone: string(255)
    locale: string(10)
    verified: boolean